---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgress-operator
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./core-operators/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: core-operators
    namespace: flux-system
  targetNamespace: postgres-operator